import Providers from '@/components/Providers'
import './globals.css'

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head />
            <title>Real-time Chat Webapp.</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
